/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Input;
import Login.Menu;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.koneksi;

/**
 *
 * @author Ridwan
 */
public class input_data_barang extends javax.swing.JFrame {
private final Connection conn = koneksi.connect();
private DefaultTableModel tabmode;
    int x;
    int y;
    /**
     * Creates new form input_data_barang
     */
    public input_data_barang() {
        initComponents();
        setLocationRelativeTo(null);
        datatable();
        jenis_barang.setSelectedItem (null);
         setLocationRelativeTo(null);

    }
protected void aktiv() {
        kode_barang.setEnabled(true);
        nama_barang.setEnabled(true);
        jumlah.setEnabled(true);
        harga.setEnabled(true);
}
protected void kosong() {
        kode_barang.setText("");
        nama_barang.setText("");
        jenis_barang.setSelectedItem (null);
        jumlah.setText("");
        harga.setText("");
        expired.setDate(null);
        keterangan.setText("");
    }
protected void datatable(){
    Object [] Baris = {"Kode Barang","Nama Barang","Jenis Barang","Jumlah","Harga","Expired","Keterangan"};
        tabmode = new DefaultTableModel(null, Baris);
        barang.setModel(tabmode);
        String sql = "select * from data_barang";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
            String a = hasil.getString("kode_barang");
            String s = hasil.getString("nama_barang");
            String d = hasil.getString("jenis_barang");
            String f = hasil.getString("jumlah");
            String g = hasil.getString("harga");
            String h = hasil.getString("expired");
            String i = hasil.getString("keterangan");
            
            String[] data={a,s,d,f,g,h,i};
            tabmode.addRow(data);
        }
    } catch (Exception e) {
        
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        barang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        keterangan = new javax.swing.JTextArea();
        harga = new javax.swing.JTextField();
        nama_barang = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        kode_barang = new javax.swing.JTextField();
        jenis_barang = new javax.swing.JComboBox<>();
        Edit = new javax.swing.JLabel();
        New = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        Save = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        expired = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(barang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 780, 220));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 100, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 170, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 170, 10));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 100, 40));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 100, 40));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 170, 10));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jumlah");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 60, 40));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 170, 10));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 50, 40));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Keterangan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 90, 40));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Expired");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 60, 40));

        keterangan.setColumns(20);
        keterangan.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        keterangan.setRows(5);
        jScrollPane2.setViewportView(keterangan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 320, 70));

        harga.setBackground(new java.awt.Color(18, 21, 25));
        harga.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        harga.setBorder(null);
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 170, 30));

        nama_barang.setBackground(new java.awt.Color(18, 21, 25));
        nama_barang.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nama_barang.setForeground(new java.awt.Color(255, 255, 255));
        nama_barang.setBorder(null);
        getContentPane().add(nama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 170, 30));

        jumlah.setBackground(new java.awt.Color(18, 21, 25));
        jumlah.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jumlah.setForeground(new java.awt.Color(255, 255, 255));
        jumlah.setBorder(null);
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 170, 30));

        kode_barang.setBackground(new java.awt.Color(18, 21, 25));
        kode_barang.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        kode_barang.setForeground(new java.awt.Color(255, 255, 255));
        kode_barang.setBorder(null);
        getContentPane().add(kode_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 130, 30));

        jenis_barang.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jenis_barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mainan Hewan", "Makanan Hewan", "Minuman Hewan", "Vaksin", "Obat" }));
        getContentPane().add(jenis_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 170, 30));

        Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditMouseExited(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, 30));

        New.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        New.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewMouseExited(evt);
            }
        });
        getContentPane().add(New, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 140, 30));

        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 140, 30));

        Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaveMouseExited(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ridwan\\Documents\\NetBeansProjects\\Skripsi\\src\\Gambar\\Barang\\Option.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 170, 200));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ridwan\\Documents\\NetBeansProjects\\Skripsi\\src\\Gambar\\Barcode.png")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, 30));

        expired.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(expired, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 170, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ridwan\\Documents\\NetBeansProjects\\Skripsi\\src\\Gambar\\Back.png")); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ridwan\\Documents\\NetBeansProjects\\Skripsi\\src\\Gambar\\Barang\\Bg.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseExited
ImageIcon AS = new ImageIcon(getClass().getResource("/Gambar/Barang/Option.png"));
jLabel9.setIcon(AS);        // TODO add your handling code here:
    }//GEN-LAST:event_SaveMouseExited

    private void SaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseEntered
ImageIcon AS = new ImageIcon(getClass().getResource("/Gambar/Barang/Option1.png"));
jLabel9.setIcon(AS);        // TODO add your handling code here:
    }//GEN-LAST:event_SaveMouseEntered

    private void EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseExited
ImageIcon AS = new ImageIcon(getClass().getResource("/Gambar/Barang/Option.png"));
jLabel9.setIcon(AS);        // TODO add your handling code here:
    }//GEN-LAST:event_EditMouseExited

    private void EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseEntered
ImageIcon AS = new ImageIcon(getClass().getResource("/Gambar/Barang/Option Edit.png"));
jLabel9.setIcon(AS);        // TODO add your handling code here:
    }//GEN-LAST:event_EditMouseEntered

    private void NewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewMouseExited
ImageIcon AS = new ImageIcon(getClass().getResource("/Gambar/Barang/Option.png"));
jLabel9.setIcon(AS);        // TODO add your handling code here:
    }//GEN-LAST:event_NewMouseExited

    private void NewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewMouseEntered
 ImageIcon AS = new ImageIcon(getClass().getResource("/Gambar/Barang/Option New.png"));
jLabel9.setIcon(AS);       // TODO add your handling code here:
    }//GEN-LAST:event_NewMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
ImageIcon AS = new ImageIcon(getClass().getResource("/Gambar/Barang/Option.png"));
jLabel9.setIcon(AS);        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMouseExited

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
 ImageIcon AS = new ImageIcon(getClass().getResource("/Gambar/Barang/Option Delete.png"));
jLabel9.setIcon(AS);       // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        new Menu().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseClicked
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(expired.getDate()));
        String sql = "insert into data_barang values(?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, kode_barang.getText());
            stat.setString(2, nama_barang.getText());
            stat.setString(3, (String)jenis_barang.getSelectedItem());
            stat.setString(4, jumlah.getText());
            stat.setString(5, harga.getText());
            stat.setString(6, tanggal);
            stat.setString(7, keterangan.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kode_barang.requestFocus();
            datatable();
            kosong();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_SaveMouseClicked

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(expired.getDate()));
        String query;
        query = "UPDATE data_barang SET nama_barang = ?, jenis_barang = ?, jumlah = ?, harga = ?, expired = ?, keterangan = ? WHERE kode_barang='"+kode_barang.getText()+"'";
        PreparedStatement statement;
        Connection connection;
        try{
            connection = koneksi.connect();
            statement = connection.prepareStatement(query);
            statement.setString(1, nama_barang.getText());
            statement.setString(2, (String)jenis_barang.getSelectedItem());
            statement.setString(3, jumlah.getText());
            statement.setString(4, harga.getText());
            statement.setString(5, tanggal);
            statement.setString(6, keterangan.getText());

            int hasil = statement.executeUpdate();
            if (hasil==1) {
                JOptionPane.showMessageDialog(this, "DATA SUKSES DIUBAH");
                kode_barang.requestFocus();
                datatable();
                kosong();
            }
        }catch(SQLException e) {
            JOptionPane.showInternalMessageDialog(this, e.getMessage());
        }         // TODO add your handling code here:
    }//GEN-LAST:event_EditMouseClicked

    private void NewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewMouseClicked
kosong();        // TODO add your handling code here:
    }//GEN-LAST:event_NewMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if(ok==0){
            String sql = "delete from data_barang where kode_barang='"+kode_barang.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kode_barang.requestFocus();
                datatable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus "+e);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMouseClicked

    private void barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangMouseClicked
        int i = barang.getSelectedRow();
   TableModel model = barang.getModel();
   kode_barang.setText(model.getValueAt(i,0).toString());
   nama_barang.setText(model.getValueAt(i,1).toString());
   jenis_barang.setSelectedItem(model.getValueAt(i,2).toString());
   jumlah.setText(model.getValueAt(i,3).toString());
   harga.setText(model.getValueAt(i,4).toString());
   keterangan.setText(model.getValueAt(i,6).toString());// TODO add your handling code here:
   // TODO add your handling code here:
    }//GEN-LAST:event_barangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input_data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input_data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input_data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input_data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input_data_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Edit;
    private javax.swing.JLabel New;
    private javax.swing.JLabel Save;
    private javax.swing.JTable barang;
    private com.toedter.calendar.JDateChooser expired;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> jenis_barang;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextArea keterangan;
    private javax.swing.JTextField kode_barang;
    private javax.swing.JTextField nama_barang;
    // End of variables declaration//GEN-END:variables
}
