/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Input;
import Login.Menu;
import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.koneksi;
import static koneksi.koneksi.conn;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Ridwan
 */
public class no_antrian extends javax.swing.JFrame {
private final Connection conn = koneksi.connect();
private DefaultTableModel tabmode;
    Statement st;
    ResultSet rs;
    PreparedStatement ps;
    String sql;
            private JasperReport jasperReport;
    private JasperPrint jasperPrint;
    private final Map<String, Object> param = new HashMap<>();
    private JasperDesign jasperDesign;
        int x;
    int y;
    /**
     * Creates new form no_antrian
     */
    public no_antrian() {
        initComponents();
                setLocationRelativeTo(null);
                datatable();
     }
    
    protected void datatable(){
    Object [] Baris = {"No Antrian","Nama Pelanggan","Status"};
        tabmode = new DefaultTableModel(null, Baris);
        antrian.setModel(tabmode);
        String sql = "select * from antrian";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
            String a = hasil.getString("no_antrian");
            String s = hasil.getString("nama_pelangggan");
            String d = hasil.getString("status");
            
            String[] data={a,s,d};
            tabmode.addRow(data);
        }
    } catch (Exception e) {
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status1 = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        delete = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        nama_pelanggan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        no_antrian = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        antrian = new javax.swing.JTable();
        clPanelTransparan2 = new PanelTransparan.ClPanelTransparan();
        no_selesai = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        clPanelTransparan1 = new PanelTransparan.ClPanelTransparan();
        jLabel4 = new javax.swing.JLabel();

        status1.setEditable(false);
        status1.setText("Selesai");

        status.setEditable(false);
        status.setText("Dalam Proses");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 70, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, -1));

        nama_pelanggan.setBackground(new java.awt.Color(102, 102, 102));
        nama_pelanggan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nama_pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        nama_pelanggan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nama_pelanggan.setBorder(null);
        getContentPane().add(nama_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 30));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nama Pelanggan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, -1));

        no_antrian.setBackground(new java.awt.Color(102, 102, 102));
        no_antrian.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        no_antrian.setForeground(new java.awt.Color(255, 255, 255));
        no_antrian.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        no_antrian.setBorder(null);
        getContentPane().add(no_antrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 30));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No Antrian");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, -1));

        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel13MouseDragged(evt);
            }
        });
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        antrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        antrian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                antrianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(antrian);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 390, 120));

        clPanelTransparan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        no_selesai.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        no_selesai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clPanelTransparan2.add(no_selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 90));

        jButton2.setText("Selesai");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        clPanelTransparan2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, -1));

        jButton3.setText("Hapus Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        clPanelTransparan2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 160, 170, -1));

        getContentPane().add(clPanelTransparan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 190, 190));

        clPanelTransparan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(clPanelTransparan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 190));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ridwan\\Documents\\NetBeansProjects\\Skripsi\\src\\Gambar\\bg2.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String sql = "insert into antrian values(?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, no_antrian.getText());
            stat.setString(2, nama_pelanggan.getText());
            stat.setString(3, status.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            no_antrian.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }         
        
        try {
            param.put("no_antrian",no_antrian.getText());
            File file = new File("src/Report/antrian.jrxml");
            jasperDesign = JRXmlLoader.load(file);
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport, param, koneksi.conn);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
        }
datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseDragged
        int mousex = evt.getXOnScreen();
        int mousey = evt.getYOnScreen();

        this.setLocation(mousex - x, mousey - y);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseDragged

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        x = evt.getX();
        y = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String query;
        query = "UPDATE antrian SET status = ? WHERE no_antrian='"+no_selesai.getText()+"'";
        PreparedStatement statement;
        Connection connection;
        try{
            connection = koneksi.connect();
            statement = connection.prepareStatement(query);
            statement.setString(1, status1.getText());


            int hasil = statement.executeUpdate();
            if (hasil==1) {
                JOptionPane.showMessageDialog(this, "Terima Kasih");
                no_selesai.requestFocus();
                datatable();
            }
        }catch(SQLException e) {
            JOptionPane.showInternalMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if(ok==0){
            String sql = "delete from antrian where no_antrian='"+delete.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                delete.requestFocus();
                datatable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus "+e);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void antrianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antrianMouseClicked
        int i = antrian.getSelectedRow();
   TableModel model = antrian.getModel();
   delete.setText(model.getValueAt(i,0).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_antrianMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */ 
         try {
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(no_antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(no_antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(no_antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(no_antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new no_antrian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable antrian;
    private PanelTransparan.ClPanelTransparan clPanelTransparan1;
    private PanelTransparan.ClPanelTransparan clPanelTransparan2;
    private javax.swing.JTextField delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nama_pelanggan;
    private javax.swing.JTextField no_antrian;
    private javax.swing.JTextField no_selesai;
    private javax.swing.JTextField status;
    private javax.swing.JTextField status1;
    // End of variables declaration//GEN-END:variables
}
